### ISSUE TITLE
Contribution for testing

### ISSUE THREAD

**Issue by ziluvatar** [IGZgustavomarin/passport-fitbit-oauth2#4]
Hi, we are integrating this module in [Auth0](https://auth0.com/), would it be possible for us to contribute to it by adding testing?

**Comment by guumaster** [comment]
Of course you can! very much welcome. We've this project a bit forgotten

**Comment by ziluvatar** [comment]
You can find the tests in this PR: https://github.com/thegameofcode/passport-fitbit-oauth2/pull/5
